//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.CustomerRoles = new HashSet<CustomerRole>();
            this.Orders = new HashSet<Order>();
        }
    
        public int CustomerID { get; set; }
        public int CustomerRoleID { get; set; }
        public string Name { get; set; }
        public string Unicode { get; set; }
        public string Address { get; set; }
        public int SalesID { get; set; }
        public string Phone { get; set; }
        public string FAX { get; set; }
        public string ContactPerson { get; set; }
        public string ContactCellPhone { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DoB { get; set; }
        public Nullable<short> status { get; set; }
        public string Password { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Status Status1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerRole> CustomerRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
