//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LatestPrice
    {
        public int RecordID { get; set; }
        public System.DateTime TransDate { get; set; }
        public string CropCode { get; set; }
        public string MarketCode { get; set; }
        public Nullable<decimal> Upper_Price { get; set; }
        public Nullable<decimal> Middle_Price { get; set; }
        public Nullable<decimal> Lower_Price { get; set; }
        public Nullable<decimal> Avg_Price { get; set; }
        public Nullable<decimal> Trans_Quantity { get; set; }
    }
}
