//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_WeeklyPrice
    {
        public int ProductID { get; set; }
        public string ProductCode { get; set; }
        public string CropCode { get; set; }
        public string Name { get; set; }
        public string Unit { get; set; }
        public string Category { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public string StatusName { get; set; }
        public Nullable<decimal> Upper_Price { get; set; }
        public string MarketName { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<decimal> Trans_Quantity { get; set; }
    }
}
